#+TITLE: README
#+DESCRIPTION: Org-export on the Indieweb
#+AUTHOR: Michael
#+EMAIL: sp1ff@pobox.com
#+DATE: <2023-04-09 Sun 15:39>
#+AUTODATE: t

* Introduction

[[https://github.com/sp1ff/indie-org][indie-org]] is an [[https://www.gnu.org/software/emacs/Emacs][Emacs]] [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Packaging-Basics][package]] for getting [[https://indieweb.org/static_site_generator][staticly-generated]] web sites published with [[https://orgmode.org/org.html][Org-mode]]'s [[https://orgmode.org/org.html#HTML-Export][HTML Export]] facility onto the [[https://indieweb.org/][Indieweb]]. The project is nascent, but I am running my sites on it. I may publish it to MELPA at some point, so I'm trying to respect both the [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html#Coding-Conventions][GNU]] and [[https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org][MELPA]] coding conventions.

User documentation may be found [[https://www.unwoundstack.com/doc/indie-org/0.5.1/indie-org.html][here]]. I've started a demonstration site [[https://indie-org.sh][here]].
* License

This code is released under the [[https://www.gnu.org/licenses/gpl-3.0.en.html][GPL version 3]].
* Prerequisites

[[https://github.com/sp1ff/indie-org][indie-org]] requires Emacs 26.1 and Org-mode 9.5.3.
* Installation

At present [[https://github.com/sp1ff/indie-org][indie-org]] is only available as source:

#+BEGIN_SRC bash
  git clone git@github.com:sp1ff/indie-org.git
  cd indie-org
  ./bootstrap
  ./configure
  make
  make check
  sudo make install
#+END_SRC

The build process _does_ make an Emacs package, so you can also do:

#+BEGIN_SRC bash
  # as above...
  make check
  make dist
#+END_SRC

to produce an Emacs package file (=indie-org-0.5.2.tar=) which you can install with =package-install-file= in your Emacs.
* Hacking

** Environment Variables

You'll probably want to setup the following environment variables:

    - =EMACS=: set this to the full path to your Emacs executable, if it's not on your =PATH=
    - =EMACSLOADPATH=: if you've got =indie-org= installed somehwere on your default load path, you'll likely want to set this while developing to ensure that Emacs always picks-up =indie-org= files in your development directories
    - =PRECOMMIT_EMACSFLAGS=: the pre-commit hook will run =package-lint= in a clean Emacs; =package-lint= which isn't built-in so use this variable to tell Emacs where to find it

The author wraps all this up in a file that he sources into his shell for development work:

#+BEGIN_SRC bash :tangle no :comments no
  #!/usr/bin/sh
  export EMACS=/opt/emacsen/current/bin/emacs
  export PRECOMMIT_EMACSFLAGS="-L ~/.emacs.d/elpa/package-lint-20221003.1636"
  export EMACSLOADPATH=$HOME/code/projects/indie-org:\
  $HOME/code/projects/indie-org/test:\
  /opt/emacsen/current/share/emacs/30.0.50/lisp
#+END_SRC
* Status & Roadmap

It's early days, and I've tried to indicate that with the version number (0.x). In order to use it successfully, you're going to need to be familiar with the [[https://orgmode.org/org.html#Exporting][Org Export]] facility and comfortable with [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html][Emacs Lisp]]. That said, it's not just an experiment: I'm using it today with my personal [[https://www.unwoundstack.com][site]].

The code base grew organically (one might say like a weed) in the first few releases, but the 0.3 series was a significant re-write in view of the lessons learned during the first iteration. The 0.5 series includes proper documentation.

I gave a [[https://www.youtube.com/watch?v=48RoqMbhftg&list=PLomc4HLgvuCUIwab7EynU78rerDXfFyR_&index=57&t=2s][talk]] on one small part of this at [[https://emacsconf.org/2022/][EmacsConf]]. I plan to host the documentation on my personal [[https://www.unwoundstack.com/doc/indie-org/0.5.1/indie-org.html][site]]. Bugs, feature requests and so on welcome!
