name: release
on:
  workflow_dispatch:
  # Modifying the push event with 'branches' and 'tags' seems to be an OR operation (i.e. the workflow
  # will run if either on branch release-infra *or* it has a tag of n.n.n)
  push:
    # Un-comment this for testing
    branches:
      - release-infra
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  # Figure-out the version and setup the artifacts directory.
  prereqs:
    name: Pre-requisites
    runs-on: ubuntu-latest
    # Un-comment this for testing
    env:
      RELEASE_VERSION: 0.4.3
    steps:
    - name: Get the release version from the tag
      if: env.RELEASE_VERSION == ''
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create artifacts directory
      run: mkdir artifacts

  # This job will actually create the artifacts I want to include with the release
  build-artifacts:
    name: build-artifacts
    runs-on: ubuntu-latest
    needs: prereqs
    steps:
    - name: Install tooling
      shell: bash
      run: |
          pwd
          set -x
          sudo apt-get install -y autoconf automake emacs
          autoconf --version
          automake --version
          emacs --version
    - name: Roll the tarballs
      shell: bash
      run: |
        set -x
        ./bootstrap && ./configure
        make all check distcheck
        echo "DISTRO_GZ=indie-org-${{ env.RELEASE_VERSION }}.tar.gz" >> $GITHUB_ENV
        echo "DISTRO_XZ=indie-org-${{ env.RELEASE_VERSION }}.tar.xz" >> $GITHUB_ENV
        echo "DISTRO_ZSTD=indie-org-${{ env.RELEASE_VERSION }}.tar.zst" >> $GITHUB_ENV
        echo "DISTRO_PKG=indie-org-${{ env.RELEASE_VERSION }}.tar" >> $GITHUB_ENV

  # This job will create the GitHub release
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs: build-artifacts
    # Un-comment this for testing
    env:
      RELEASE_VERSION: 0.4.3
    steps:
      - name: Get the release version from the tag
        if: env.RELEASE_VERSION == ''
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "${{ env.DISTRO_GZ }},${{ env.DISTRO_XZ }},${{ env.DISTRO_ZSTD }},${{ env.DISTRO_PKG }}"
          draft: true

  
